### ISSUE TITLE
Docs aren't building correctly.

### ISSUE THREAD

**Issue by daffidwilde** [daffidwilde/matching#104]
Despite the changes in #103, the documentation still does not build correctly. I've been attempting manual wipes on readthedocs.org but there is no consistency.

**Comment by daffidwilde** [comment]
Note that building locally does not cause this problem but also does not specify the commit ("Revision") for any page:

```
git clone https://github.com/daffidwilde/matching.git
cd matching
conda create --file docs/environment.yml
conda activate matching-docs
sphinx-build -b html docs docs/_build/html
```

**Comment by mgeier** [comment]
Are you sure this isn't just a matter of your browser cache?
Did you hit "refresh"?

**Comment by daffidwilde** [comment]
Ah, I hadn't thought about my cache 😅

I had been loading/refreshing across multiple browsers on both my phone and laptop but I guess they all still had that version cached somewhere. Clearing everything out solved the issue and I'll close this now.

Thanks @mgeier!
