### ISSUE TITLE
Update pypi link to documentation

### ISSUE THREAD

**Issue by isocolon** [daffidwilde/matching#168]
The [pypi page](https://pypi.org/project/matching/) says that documentation is available at https://matching.readthedocs.io/. However, this is a bad link. Per the info on this Github repo, the correct link is https://daffidwilde.github.io/matching/.

**Comment by daffidwilde** [comment]
Hi @isocolon 👋🏼 this was fixed in #164 but I am yet to release a new version on PyPI. Thanks for the nudge - I will do that now.

**Comment by daffidwilde** [comment]
`matching@1.4.3` is available [on PyPI](https://pypi.org/project/matching/) now 🚀
