### ISSUE TITLE
function called resident_hospital instead of hospital_resident?

### ISSUE THREAD

**Issue by chen7572** [daffidwilde/matching#27]
I installed matching to use, but noticed that when I tried to call a function, the resident_hospital came up, instead of hospital_resident in your tutorial. The version I installed is 0.1.1. I wonder if there are different versions of this library that I may not be getting the most updated one? 

Thank you!

**Comment by AMarsCitizen** [comment]
I was wondering the same. Are there different versions ?
Thank you!

**Comment by reinoldus** [comment]
Yes, I encountered the same issue. It seems like the version in the pip-repo is older than the master branch.

**Comment by daffidwilde** [comment]
Hello everyone!

Sorry for all the confusion. I am in the process of updating/rebuilding the library and so there are various versions out there that may not be compatible or consistent with the documentation. I appreciate your patience over the next week or so while I prepare the next release.

**Comment by AMarsCitizen** [comment]
Hey i just saw the update i am checking that now !! Thanks for sharing man !!I I did my own implementating of the capacitated hospital-resident algorithm and i have a 93% matching success(number of students(suitors) matched / total number of students ) on a suitors set of 300 students and 43 projects of capacities ranging between 6 and 14 students . But i don't have a very good pre-processing to correctly rank the students on the project_pref_dict (aka reviewers_pref_dict) i think that's what's keeping me from hitting that sweet 99% or 100% matching success.
I'll use ur new algo i hope it can go over the 93% matching sucess.
Thanks again mate !!

**Comment by daffidwilde** [comment]
Hopefully the new release is useful to you all 👍

I'm closing this issue but feel free to get in contact if you have any other queries
