### ISSUE TITLE
stable roommate problem

### ISSUE THREAD

**Issue by mkleinbort** [daffidwilde/matching#64]
Hi, 

Do you plan to have a solution for https://youtu.be/9Lo7TFAkohE

I.e. the marriage problem, but where there is no given partition into boys/girls

Rather, you have _n_ people each with an internal preference for the other _n-1_ people. And you have to pair them as "roommates".

**Comment by daffidwilde** [comment]
Hi there,

I would love to implement the stable roommates problem into the library -- or any other matching games for that matter. I don't have masses of spare time at the moment but if you fancied opening a PR with an implementation, I'd be very happy to collaborate.

**Comment by daffidwilde** [comment]
This is now implemented as of #65 on the master branch, and will be included in the next release.
